modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
issueTrackerURL="https://github.com/RecraftorsMC/Advancement-Cascade/issues"
[[mods]]
modId="advancement_cascade"
version="${version}"
displayName="Advancement Cascade"
#updateJSONURL="http://myurl.me/"
displayURL="https://github.com/RecraftorsMC/Advancement-Cascade"
authors="Nerjal Nosk, RecraftorsMC"
displayTest="IGNORE_SERVER_VERSION"
description='''
Adds advancement-based advancement triggers
'''
[[dependencies.advancement_cascade]]
   modId="forge"
   mandatory=true
   versionRange="[40,)"
   ordering="NONE"
   side="SERVER"
[[dependencies.advancement_cascade]]
   modId="minecraft"
   mandatory=true
   versionRange="[1.19,1.20)"
   ordering="NONE"
   side="SERVER"
